version: '3.8'

services:
 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
      MYSQL_DATABASE: 'safeaccountsapi_db'    
      MYSQL_USER: 'user'     
      MYSQL_PASSWORD: 'password'    
      MYSQL_ROOT_PASSWORD: 'password'
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql:
  mysql_config: